spring:
  profiles:
    active: 
    - dev
---

server:
  port: 1001
spring:
  profiles: dev
  application:
    name: ddddd-dev

---

server:
  port: 1002
spring:
  profiles: uat
  application:
    name: uuuuu-uat